Now/Controllers/LicencaVendedoresController.cs
using Now.Domain;
using Now.Models;
using Now.Domain.Contracts.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Now.Controllers
{
    public class LicencaVendedoresController : BaseController
    {
        public IVendedoresLicenciadosService _serviceLicencaVendedores;
        public LicencaVendedoresController(IVendedoresLicenciadosService serviceLicencaVendedores)
        {
            _serviceLicencaVendedores = serviceLicencaVendedores;

        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult SalvarLicenca(string lojaId, string vendedorId, string motivoId, string dataInicial, string dataFinal, string tbxObservacao, string flgIndeterminado)
        {
            try
            {

                VendedoresLicenciados licenca = new VendedoresLicenciados();
                licenca.loja_id = Convert.ToInt32(lojaId);
                licenca.vendedor_id = Convert.ToInt32(vendedorId);
                licenca.vendedor_licenciados_tipo_id = Convert.ToInt32(motivoId);

                if (Convert.ToInt32(flgIndeterminado) == 0)
                {
                    licenca.data_inicio_bloqueio = Convert.ToDateTime(dataInicial);
                    licenca.data_fim_bloqueio = Convert.ToDateTime(dataFinal);
                }

                licenca.data_inclusao = DateTime.Now;
                licenca.data_alteracao = DateTime.Now;
                licenca.motivo = tbxObservacao;
                licenca.flg_bloqueio_indeterminado = Convert.ToInt32(flgIndeterminado);
                licenca.data_desativacao = null;

                _serviceLicencaVendedores.Salvar(licenca);
                var _list = _serviceLicencaVendedores.Listar(lojaId, vendedorId);

                return Json(new { success = true, msg = "Licença salva com sucesso!", dados = _list });

            }
            catch (Exception ex)
            {
                return Json(new { success = false, msg = "Erro ao salvar a licença!" });
            }
        }

        public JsonResult ListarMotivos()
        {
            try
            {
                var listTipo = _serviceLicencaVendedores.ListarMotivos();

                return Json(new { data = listTipo, success = true, msg = "Licença salva com sucesso!" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, msg = "Erro ao salvar a licença!" });
            }
        }

        public JsonResult ListarLicencaVendedores(string lojaId, string vendedorId)
        {
            try
            {
                var _list = _serviceLicencaVendedores.Listar(lojaId, vendedorId);

                return Json(new { dados = _list });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, msg = "Erro ao salvar a licença!" });
            }
        }

    }
}

Now/Views/LicencaVendedores/Index.cshtml
@{
    ViewBag.Title = "Vendedores Afastados";
}


<div class="row">
    <div class="col-md-4">
        <div class="box box-danger">
            <div class="box-header">
                <h3 class="box-title">Cadastrar Afastamento</h3>
            </div>
            <div class="box-body">

                <div class="form-group">
                    <label>Loja</label>
                    @if (((SelectList)ViewBag.LojasFiltrado).Count() > 1)
                    {
                        @Html.DropDownList("loja_id",
                            (SelectList)ViewBag.LojasFiltrado,
                            new { @class = "form-control select2", @style = "width: 100%;", @onchange = "onVendedorChange('vendedor_id');", required = "required" })
                    }
                    else
                    {
                        <h4 class="text-center">@Html.Label("loja_id", (String)ViewBag.NomeLojaSelecionada)</h4>
                    }
                </div>

                <div class="form-group">
                    <label>Vendedor</label>
                    @if (String.IsNullOrEmpty(ViewBag.Idvendedor))
                    {
                        @Html.DropDownList("vendedor_id"
                            , (SelectList)ViewBag.Vendedores
                            , new { @class = "form-control select2", @style = "width: 100%;", required = "required" })
                    }
                    else
                    {
                        <h4 class="text-center">@Html.Label("vendedor_id", (String)ViewBag.NomeSelecionadoCompleto)</h4>
                    }
                </div>


                <div class="form-group">
                    <label>Motivo</label>
                    @Html.DropDownList("motivo_id"
                            , (SelectList)ViewBag.Vendedores
                            , new { @class = "form-control select2", @style = "width: 100%;", required = "required" })
                </div>

                <div class="form-group">
                    <label>Tempo?</label>
                    @Html.DropDownList("flgIndeterminado"
                            , new List<SelectListItem>{
                                new SelectListItem { Text = "Selecione", Value = "", Selected = true },
                                new SelectListItem { Text = "Por Período", Value = "0" },
                                new SelectListItem { Text = "Indeterminado", Value = "1" }
                            }
                            , new { @class = "form-control select2", @style = "width: 100%;", required = "required" })
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Data Inicial</label>
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                @Html.TextBox("data_inicial", "", new { @class = "form-control text-center datepickerRangeFrom", required = "required", data_provide = "datepicker", placeholder = "dd/mm/yyyy" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Data Final</label>
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                @Html.TextBox("data_final", "", new { @class = "form-control text-center datepickerRangeTo", required = "required", data_provide = "datepicker", placeholder = "dd/mm/yyyy" })
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label>Observações</label>
                    @Html.TextArea("tbxObservacao", new { @class = "form-control ", @rows = "6", @style = "width: 100%;" })
                </div>




            </div>

            <div class="box-footer">
                <button type="button" id="btnCancelar" name="btnCancelar" class="btn2-gradient red btnCancelar text-uppercase text-bold"><i class="glyphicon glyphicon-remove"></i> Cancelar</button>
                <button type="button" id="btnSalvar" name="btnConfirmar" class="btn2-gradient green btnSalvar text-uppercase text-bold pull-right"><i class="glyphicon glyphicon-ok"></i> Salvar</button>
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Afastados</h3>
            </div>
            <div class="box-body">

                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>Vendedor</th>
                            <th>Data Inicial</th>
                            <th>Data Final</th>
                            <th>Motivo</th>
                            <th>Status</th>
                            <th>Observações</th>
                            <th>Ações</th>
                        </tr>
                        <tr id="listaAfastados">
                            <td>John Doe</td>
                            <td>11-7-2014</td>
                            <td>11-7-2014</td>
                            <td>FÉRIAS</td>
                            <td><span class="label label-success">Approved</span></td>
                            <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                            <td>
                                <a href="#"><i class="glyphicon glyphicon-pencil"></i></a>
                                <a href="#"><i class="glyphicon glyphicon-trash"></i></a>
                                <a href="#"><i class="glyphicon glyphicon-arrow-down"></i></a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script type="text/javascript">
        $("#btnSalvar").click(function (e) {
            loading();

            var validacao = true;
            var lojaId = $("#loja_id").val();
            var vendedorId = $("#vendedor_id").val();
            var motivoId = $("#motivo_id").val();
            var dataInicial = $("#data_inicial").val();
            var dataFinal = $("#data_final").val();
            var tbxObservacao = $("#tbxObservacao").val();
            var flgIndeterminado = $("#flgIndeterminado").val();

            if (validacao) {

                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("SalvarLicenca", "LicencaVendedores")',
                    dataType: 'json',
                    data: { lojaId: lojaId, vendedorId: vendedorId, motivoId: motivoId, dataInicial: dataInicial, dataFinal: dataFinal, tbxObservacao: tbxObservacao, flgIndeterminado: flgIndeterminado },
                    success: function (result) {
                        if (result.success) {
                            $.msg({ content: result.msg, tipo: 'alert-success', titulo: 'Sucesso', img: 'fa-check' });
                        } else {

                        }
                        //ListarClienteNovo();
                        //CancelarCadastroNovo();
                        $.unblockUI();
                    },
                    complete: function () {
                        $.unblockUI();
                    },
                    error: function (ex) {
                        $.unblockUI();
                    }
                });
                $.unblockUI();
            }
            return false;
        });

        ListarMotivos();

        function ListarMotivos()
        {
            $("#motivo_id").empty();

            $.ajax({
                type: 'POST',
                url: '@Url.Action("ListarMotivos", "LicencaVendedores")',
                dataType: 'json',
                success: function (result) {
                    if (result.success) {
                        $.each(result.data, function (i, item) {
                            $("#motivo_id").append('<option value="' + item.id + '">' + item.nome + '</option>');
                        });
                    } else {

                    }
                    //ListarClienteNovo();
                    //CancelarCadastroNovo();
                    $.unblockUI();
                },
                complete: function () {
                    $.unblockUI();
                },
                error: function (ex) {
                    $.unblockUI();
                }
            });
        }

    </script>
}